### ISSUE TITLE
node-simconnect Does not compile for Electron

### ISSUE THREAD

**Issue by kdlovell** [EvenAR/node-simconnect#12] opened 2020-04-30 00:46 UTC
Hello,

I cloned the master branch and was able to successfully compile node-simconnect as a 64bit module against the P3D V5 SDK.  I tested it and it worked perfectly!

I then tried to rebuild node-simconnect for Electron and ran into a slew of errors.  
nodejs version = 12.6.2
electron version = 8.2.4

Admittedly, this is my venture into node js and electron so I may be making a newbie mistake.  I used the following command: .\node_modules\.bin\electron-rebuild

Log is here:
https://pastebin.com/Mf77u5PJ

Thanks!

**Comment by jgbijlsma** [comment] 2020-09-01 09:43
I have the same error. Would love to hear a solution

**Comment by westlakem** [comment] 2020-09-15 22:42
I have a very similar issue as @jgbijlsma 

Did the owner abandon this project?  I've tried to fix the addon.cc file, but I'm just not familiar enough with C++.  I found a solution to the `cannot convert from 'v8::MaybeLocal<v8::String>' to 'v8::Local<v8::String>'` problem, but the `Get` and `Set` functions are blowing up and any of the darts I've thrown at the wall don't seem to work (shooting in the dark on those because again... not a C++ programmer).

@EvenAR

**Comment by westlakem** [comment] 2020-09-18 23:06
@kdlovell @jgbijlsma @josehfortes @EvenAR 

I've done some work on the addon.cc file to update it for electron version 10.  Note that this will break non-electron projects, and won't work with "rebuild" but instead needs to be built specifically for electron (I used the `electron-rebuild` package).  There are still many functions not incorporated into this library, but it's a good starting point.  Just replace the contents of your `addon.cc` file with this one.

https://gist.github.com/westlakem/17910065569d21066d038667537e48ee

Hope this helps!

**Comment by EvenAR** [comment] 2020-09-19 15:48
I'm sorry for not being very helpful here. Thanks a lot for sharing your solution, @westlakem 👍 

FYI I have started on a major refactoring which will be based on the [node-addon-api](https://github.com/nodejs/node-addon-api). It will no longer depend directly on `v8` and `nan`, which will make the code easier to maintain.

**Comment by josehfortes** [comment] 2020-09-19 18:34
No problem @EvenAR, I'm thankful for your job on this project.

Thanks @westlakem for your help! I appreciate that.

**Comment by westlakem** [comment] 2020-09-21 17:38
@EvenAR glad to hear you're continuing to work on this project!  Do you have an estimated release date for that refactor?  Trying to determine for my project if it's worth putting in the time on the current version or if I should just focus on other parts.  If you need a beta tester let me know!

**Comment by yordadev** [comment] 2020-10-06 16:32
Just attempted this. 

```sh
$ npm run make

> electron-webview@1.0.6 make C:\Users\USERNAME\Desktop\Virtual_Airline\VirtualAirlineClient
> electron-forge make

- Checking your system
ΓêÜ Checking your system
- Resolving Forge Config
ΓêÜ Resolving Forge Config
We need to package your application before we can make it
- Preparing to Package Application for arch: ia32
ΓêÜ Preparing to Package Application for arch: ia32
- Preparing native dependencies
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(399,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\USERNAME\AppData\Local\Temp\electron-packager\win32-ia32\Virtual-Airline-Client-win32-ia32\resources\app\node_modules\node-simconnect\build\node-simconnect.vcxproj]
  addon.cc
  win_delay_load_hook.cc
c:\users\USERNAME\appdata\local\temp\electron-packager\win32-ia32\virtual-airline-client-win32-ia32\resources\app\node_modules\node-simconnect\10.1.2\include\node\v8.h(5378): warning C4309: 'static_cast': truncation of constant value (compiling source file ..\src\addon.cc) [C:\Users\USERNAME\AppData\Local\Temp\electron-packager\win32-ia32\Virtual-Airline-Client-win32-ia32\resources\app\node_modules\node-simconnect\build\node-simconnect.vcxproj]
c:\users\USERNAME\appdata\local\temp\electron-packager\win32-ia32\virtual-airline-client-win32-ia32\resources\app\node_modules\node-simconnect\10.1.2\include\node\v8.h(9113): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (compiling source file ..\src\addon.cc) [C:\Users\USERNAME\AppData\Local\Temp\electron-packager\win32-ia32\Virtual-Airline-Client-win32-ia32\resources\app\node_modules\node-simconnect\build\node-simconnect.vcxproj]
  c:\users\USERNAME\appdata\local\temp\electron-packager\win32-ia32\virtual-airline-client-win32-ia32\resources\app\node_modules\node-simconnect\10.1.2\include\node\v8.h(7322): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\addon.cc)
c:\users\USERNAME\appdata\local\temp\electron-packager\win32-ia32\virtual-airline-client-win32-ia32\resources\app\node_modules\node-simconnect\10.1.2\include\node\v8.h(9121): warning C4996: 'v8::MicrotasksCompletedCallback': Use *WithData version. (compiling source file ..\src\addon.cc) [C:\Users\USERNAME\AppData\Local\Temp\electron-packager\win32-ia32\Virtual-Airline-Client-win32-ia32\resources\app\node_modules\node-simconnect\build\node-simconnect.vcxproj]
  c:\users\USERNAME\appdata\local\temp\electron-packager\win32-ia32\virtual-airline-client-win32-ia32\resources\app\node_modules\node-simconnect\10.1.2\include\node\v8.h(7322): note: see declaration of 'v8::MicrotasksCompletedCallback' (compiling source file ..\src\addon.cc)
c:\users\USERNAME\appdata\local\temp\electron-packager\win32-ia32\virtual-airline-client-win32-ia32\resources\app\node_modules\node-simconnect\src\addon.h(5): fatal error C1083: Cannot open include file: 'SimConnect.h': No such file or directory (compiling source file ..\src\addon.cc) [C:\Users\USERNAME\AppData\Local\Temp\electron-packager\win32-ia32\Virtual-Airline-Client-win32-ia32\resources\app\node_modules\node-simconnect\build\node-simconnect.vcxproj]
├ù Preparing native dependencies: 0 / 1

An unhandled error has occurred inside Forge:
node-gyp failed to rebuild 'C:\Users\USERNAME\AppData\Local\Temp\electron-packager\win32-ia32\Virtual-Airline-Client-win32-ia32\resources\app\node_modules\node-simconnect'.
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1


Error: node-gyp failed to rebuild 'C:\Users\USERNAME\AppData\Local\Temp\electron-packager\win32-ia32\Virtual-Airline-Client-win32-ia32\resources\app\node_modules\node-simconnect'.
Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1


    at ModuleRebuilder.rebuildNodeGypModule (C:\Users\USERNAME\Desktop\Virtual_Airline\VirtualAirlineClient\node_modules\electron-rebuild\src\module-rebuilder.ts:186:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-webview@1.0.6 make: `electron-forge make`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-webview@1.0.6 make script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\USERNAME\AppData\Roaming\npm-cache\_logs\2020-10-06T16_27_23_416Z-debug.log
```

**Comment by riccardolardi** [comment] 2020-10-11 15:29
Subscribing - also looking for a solution to build this against latest electron.

**Comment by riccardolardi** [comment] 2020-10-20 17:26
@EvenAR is the refactor branch supposed to work for building with electron on x64? I'm getting an error `simconnect_session.cc(398,27): error C2397: conversion from 'unsigned __int64' to 'uint32_t' requires a narrowing conversion`

What is the current way to get it working for electron x64? Using @westlakem addons.cc mod? Using that and after either rebuilding with node-gyp or with electron-rebuild no matter I get an error saying the module was built against node 82 but is expected to be built for node v72. Using latest electron 10.1.4.

Thanks for any advice!

**Comment by jgbijlsma** [comment] 2020-11-27 16:03
I'm failing to get node-simconnect build and running for electron with the master branch. In the refactor branch I get the following errors:

$ HOME=~/.electron-gyp node-gyp rebuild --target=11.0.3 --arch=x64 --msvs_version=2017 --dist-url=https://electronjs.org/headers
gyp info it worked if it ends with ok
gyp info using node-gyp@7.1.2
gyp info using node@12.18.4 | win32 | x64
gyp info find Python using Python version 2.7.15 found at "C:\Users\jbijl\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.1300) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\jbijl\.windows-build-tools\python27\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Users\\jbijl\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\coding\\simcareer-electron\\node_modules\\node-simconnect-refactor\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jbijl\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\jbijl\\AppData\\Local\\node-gyp\\Cache\\11.0.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\jbijl\\AppData\\Local\\node-gyp\\Cache\\11.0.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\jbijl\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\jbijl\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\11.0.3\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\coding\\simcareer-electron\\node_modules\\node-simconnect-refactor',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\coding\\simcareer-electron\\node_modules\\node-simconnect-refactor\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
←[37;40mgyp←[0m ←[0m←[32minfo←[0m ←[0m←[35mspawn←[0m C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe
←[0m←[37;40mgyp←[0m ←[0m←[32minfo←[0m ←[0m←[35mspawn args←[0m [
←[0m←[37;40mgyp←[0m ←[0m←[32minfo←[0m ←[0m←[35mspawn args←[0m   'build/binding.sln',
←[0m←[37;40mgyp←[0m ←[0m←[32minfo←[0m ←[0m←[35mspawn args←[0m   '/clp:Verbosity=minimal',
←[0m←[37;40mgyp←[0m ←[0m←[32minfo←[0m ←[0m←[35mspawn args←[0m   '/nologo',
←[0m←[37;40mgyp←[0m ←[0m←[32minfo←[0m ←[0m←[35mspawn args←[0m   '/p:Configuration=Release;Platform=x64'
←[0m←[37;40mgyp←[0m ←[0m←[32minfo←[0m ←[0m←[35mspawn args←[0m ]
←[0mBuilding the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  simconnect_session.cc
d:\coding\simcareer-electron\node_modules\node-simconnect-refactor\src\simconnect_session.cc(434): error C2397: conversion from 'unsigned __int64' to 'unsigned i
nt' requires a narrowing conversion [D:\coding\simcareer-electron\node_modules\node-simconnect-refactor\build\node_simconnect.vcxproj]
←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mbuild error←[0m 
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at ChildProcess.onExit (C:\Users\jbijl\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at ChildProcess.emit (events.js:315:20)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mstack←[0m     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mSystem←[0m Windows_NT 10.0.19041
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mcommand←[0m "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\jbijl\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=11.0.3" "--arch=x64" "--msvs_version=2017" "--dist-url=https://electronjs.org/headers"
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mcwd←[0m D:\coding\simcareer-electron\node_modules\node-simconnect-refactor
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnode -v←[0m v12.18.4
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnode-gyp -v←[0m v7.1.2
←[0m←[37;40mgyp←[0m ←[0m←[31;40mERR!←[0m ←[0m←[35mnot ok←[0m
←[0m

**Comment by EvenAR** [comment] 2020-11-27 17:44
@jgbijlsma could you try the refactor branch again now? https://github.com/EvenAR/node-simconnect/commit/e745f996aca0d4278aa7f19332d632ee0340c681 should have fixed the problem.

**Comment by megasus** [comment] 2020-12-01 18:29
@EvenAR Unfortunately, Im also struggling to make this library work with electron. Compiling works, but I get this error when running the app:
![image](https://user-images.githubusercontent.com/753424/100781234-11a14b80-340b-11eb-95f2-2313d7fa9727.png)
Steps to reproduce:
- Clone Electron Quickstart: https://github.com/electron/electron-quick-start
- npm install electron-rebuild
- npm install evenar/node-simconnect#refactor
- go to node_modules/node-simconnect and run `npm install`
- go to project root, run `.\node_modules\.bin\electron-rebuild.cmd`
- modify main.js:
![image](https://user-images.githubusercontent.com/753424/100781630-8bd1d000-340b-11eb-8aa4-1a5a5483b42d.png)

**Comment by riccardolardi** [comment] 2020-12-01 18:31
@megasus make sure you have the MS C++ redistributables installed: https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by megasus** [comment] 2020-12-01 18:52
@riccardolardi Thanks for your response. That didn't help unfortunately. Do you have an electron app working?

**Comment by riccardolardi** [comment] 2020-12-01 19:10
@megasus yes, and I remember I solved a similar JS error by installing the redistributables. Not sure anymore though about the exact error message so it might have been another case. You can check my code here if it helps: https://github.com/riccardolardi/fsmaptool-server

**Comment by megasus** [comment] 2020-12-01 20:10
@riccardolardi You are using x64 architecture, right? What version of simconnect did you use? The x64 Prepar3d version? I'm trying to compile your app against ia32 with 32bit node, but I get exactly the same errors compared to my demo app.

**Comment by EvenAR** [comment] 2020-12-12 15:09
@megasus this works for me using the latest beta and Electron 11.0.5:
1. Create a basic Electron project based on: https://www.electronjs.org/docs/tutorial/quick-start
1. From the project root directory run 
    ```
    npm install --save node-simconnect@beta
    cd node_modules/node-simconnect
    # Install dev-dependencies:
    npm install
    mkdir SimConnect/inc SimConnect/lib
    ```
1. Move the SDK files to their respective `lib`/`inc`-folders
1. Run `HOME=~/.electron-gyp node-gyp rebuild --target=11.0.5 --arch=ia32 --dist-url=https://electronjs.org/headers`
1. Import the module in `main.js`: 
    ```js
    const { SimConnect } = require("node-simconnect")
    ```

**Comment by EvenAR** [comment] 2022-09-24 15:53
I'm closing this as the new version works natively with Electron.

**Closed by EvenAR** 2022-09-24 15:53 UTC
